### ISSUE TITLE
False negative 'login successful' on wrong email

### ISSUE THREAD

**Issue by maximunited** [Dvirus89/tenbisbarcodes#3]
```
$ python3 tenbis-report.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Enter email: jdoe@no_such_domain.com
login successful
Traceback (most recent call last):
  File "tenbis-report.py", line 236, in <module>
    main_procedure()
  File "tenbis-report.py", line 107, in main_procedure
    session = auth_tenbis()
  File "tenbis-report.py", line 211, in auth_tenbis
    auth_token =  resp_json['Data']['codeAuthenticationData']['authenticationToken']
TypeError: 'NoneType' object is not subscriptable
```
I accidentally entered an extra char in my real email. And took me a couple of mins to notice my mistake b/c it actually said 'login successful'

In any case, this project is f-ing amazing! Actually found me free money!!! Keep up the great work!

**Comment by Dvirus89** [comment]
Hi Max,
Thank you!

Fixed here:
https://github.com/Dvirus89/tenbisbarcodes/commit/25cee74ba63009203ae33f1058648142a68e5de6
